### ISSUE TITLE
Problem with installing plugin.

### ISSUE THREAD

**Issue by mijoharas** [negesti/gnome-shell-extensions-negesti#73] opened 2015-03-23 12:20 UTC
from `.xsession-errors` I have:

```
Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x2e00003 (GNOME Shel)
Window manager warning: meta_window_activate called by a pager with a 0 timestamp; the pager needs to be fixed.
Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x3000003 (GNOME Shel)
Window manager warning: meta_window_activate called by a pager with a 0 timestamp; the pager needs to be fixed.
```

There are other things that may be affecting it. My `gnome-shell` version is `GNOME Shell 3.4.1` and my distro is ubuntu 12.05 LTS. any ideas?

**Comment by mijoharas** [comment] 2015-03-23 12:27
To clarify, on clicking `install` on the web interface it then says `error` on the webpage after downloading, other plugins have been downloaded and work correctly (and putWindows works fine on my other computer).

**Comment by mijoharas** [comment] 2015-03-24 15:56
confirmed this on a fresh installation. is `ubuntu 12.04 LTS` and gnome shell `3.4.1` supported?

**Comment by negesti** [comment] 2015-03-24 16:18
3.4.1 should work.
have you tried to manually install the extension? e.g. 
 checkout from github,
 copy/link to ~/.local/share/gnome-shell/extensions/putWindow@clemens.lab21.org
 enable using gnome-tweek-tool

**Comment by mijoharas** [comment] 2015-03-24 16:36
I tried but it didn't work at the time. I'll try again and see whether it works, given your instructions. btw, where should I be looking for logs?

**Comment by negesti** [comment] 2015-03-24 16:37
finding logs in gnome-shell is always a little bit hard. 
the easiest way is to run gnome-shell from a terminal, and let it log there 
e.g.
 gnome-shell --replace &

the & is important ;)

**Comment by mijoharas** [comment] 2015-03-24 16:57
so I get the same behaviour. I've been trying a bunch of things and can't seem to find the right logs either.

**Comment by mijoharas** [comment] 2015-03-24 17:00
to be clear about the behaviour, the switch to turn it on or off does nothing, if I flip that switch (either locally or through the gnome-extensions web page) while the web-page is open I sometimes see an error symbol on the web page where there would normally be the check-box that turns it off or on. I can correctly open the settings of the application. I think this may actually be an error related to running rather than installation as I said before.

**Comment by mijoharas** [comment] 2015-03-24 17:03
oh and running `gnome-shell --replace &` in a terminal (gnome-terminal) gives a bit of output but no more after that. it says:

```
Window manager warning: Log level 16: STACK_OP_REMOVE: window 0x5d not in stack

(gnome-shell:7450): folks-WARNING **: Failed to find primary PersonaStore with type ID 'eds' and ID 'system'.
Individuals will not be linked properly and creating new links between Personas will not work.
The configured primary PersonaStore's backend may not be installed. If you are u
```
and then gets cut off by the next input line and doesn't log any further.

**Comment by negesti** [comment] 2015-03-25 08:09
very strange. i will install a virtual machine and try your setup.

**Comment by negesti** [comment] 2015-03-25 08:31
how did you install gnome-shell? just apt-get install gnome-shell (from universe)

**Comment by mijoharas** [comment] 2015-03-25 09:45
`sudo apt-get install gnome` hadn't made any changes to `apt-get` settings so I assume it's universe (I come from another distro, so not intimately familiar with `apt-get`).

Oh and one small thing, I assumed it shouldn't matter, but I kept `lightdm` rather than replacing it with `gdm`. I'm think since they're login managers it shouldn't make a difference, but thought I'd mention it.

**Comment by negesti** [comment] 2015-03-26 09:34
installed a vm (with really bad graphic performance) and tested it.

The current develop version doesn't work. However you can checkout v15 and everything should be fine. Note, that in v15 the extension files are in a subfolder, you have to update your symbolic link 

asuming you have checkout the repo into ~/workspace/gnome-shell-extensions-negesti
```
        git checkout v15
        ln -s ~/workspace/gnome-shell-extensions-negesti/putWindow\@clemens.lab21.org ~/.local/share/gnome-shell/extensions/
```

restart the shell (alt + F2 -> r -> enter) and it should work

**Comment by negesti** [comment] 2015-03-26 10:52
ok found it, develop should work now

**Comment by mijoharas** [comment] 2015-03-26 12:13
hmm... that worked... not sure why it didn't work before. Thanks for the help, closing this. :+1:

**Comment by mijoharas** [comment] 2015-03-26 12:15
Oh, one more question, is it possible to move fullscreen windows to another screen (e.g. make window fullscreen with `F12` and then `Super+Shift+Right` to move it)?

**Comment by negesti** [comment] 2015-03-27 09:46
just found a problem with the padding calculation. you should pull the new version

**Comment by mijoharas** [comment] 2015-03-27 10:12
Thanks!

**Comment by mijoharas** [comment] 2015-03-27 10:41
Hmmm, not sure I should have closed this, I can't get it to work with develop, but can with `v15`. Just to eliminate me as a potential source of messing things up I'll show you what I did (there are also some bugs compared to how it works on my other machine, I'll document them here just in case that helps figure things out. for develop, to install I do:

```
rm -rf ~/.local/share/gnome-shell/extensions/*
git clone git@github.com:negesti/gnome-shell-extensions-negesti.git
cd gnome-shell-extensions-negesti
git co develop
cd ..
cp gnome-shell-extensions-negesti ~/.local/share/gnome-shell/extensions/putWindow@clemens.lab21.org
# reset gnome-shell with `Alt-F2` then `r`
gnome-tweak-tool
# enable put windows plugin
```
This does not work (it seems enabled, but I cannot use the plugin, I tend to test with `Super+Shift+Left`  or right, which doesn't work).
to install v15 which works for me (with caveats, see below) I did:

```
rm -rf ~/.local/share/gnome-shell/extensions/*
cd gnome-shell-extensions-negesti
git co v15
cp putWindow@clemens.lab21.org ~/.local/share/gnome-shell/extensions/
# reset gnome-shell with `Alt-F2` then `r`
gnome-tweak-tool
# enable put windows plugin
```
So v15 doesn't work perfectly for me. I can do `Super+Shift+Right` and left, but only if the window is not already snapped to a side (with `Super+Right`). It can be moved between screens when maximised, but only if it hasn't been snapped to the side first.

**Comment by mijoharas** [comment] 2015-03-27 10:44
I feel like I could be more helpful if I could give you logs, but as I said, `gnome-shell --replace &` does successfully replace the shell in the background, but doesn't log to the gnome-terminal after a few lines (always looks cut off). Let me know if there is another way to get logs, or if I'm doing something wrong.

**Comment by 73** [comment] 2015-03-27 10:49
The extension does not work with snapped windows. Its a known issue.

**Comment by mijoharas** [comment] 2015-03-27 11:24
ok, thanks. I've done a little more digging, looking into what's happening in my setup. It still doesn't work in develop, it does enable, it doesn't emit any errors (in looking-glass). Ok, scratch that, it does emit errors, looking glass just handily lies to me and says it doesn't. I figured out the `gnome-shell --replace &` thing, (my modeline was overwriting it or something, I get output once I removed my `.zshrc` The error I get is:

```
    JS ERROR: !!!   Exception was: TypeError: global.screen.get_monitor_index_for_rect is not a function
    JS ERROR: !!!     lineNumber = '327'
    JS ERROR: !!!     fileName = '"/home/local/ANT/hauserra/.local/share/gnome-shell/extensions/putWindow@clemens.lab21.org/moveFocus.js"'
    JS ERROR: !!!     stack = '"("l")@/home/local/ANT/hauserra/.local/share/gnome-shell/extensions/putWindow@clemens.lab21.org/moveFocus.js:327
([object _private_Meta_Display],[object _private_Meta_Screen],null,[object _private_Meta_KeyBinding])@/home/local/ANT/hauserra/.local/share/gnome-shell/extensions/putWindow@clemens.lab21.org/moveFocus.js:147
"'
    JS ERROR: !!!     message = '"global.screen.get_monitor_index_for_rect is not a function"'
```

**Comment by negesti** [comment] 2015-03-27 12:11
should be fixed. 
feature back ported ;)

**Comment by mijoharas** [comment] 2015-03-27 14:45
almost, I can now go from my left screen to my right screen, but not vice-versa :smile:.

```
     JS ERROR: !!!   Exception was: TypeError: this._screens is undefined
    JS ERROR: !!!     lineNumber = '362'
    JS ERROR: !!!     fileName = '"/home/mike/.local/share/gnome-shell/extensions/putWindow@clemens.lab21.org/moveFocus.js"'
    JS ERROR: !!!     stack = '"([object _private_Meta_Window])@/home/mike/.local/share/gnome-shell/extensions/putWindow@clemens.lab21.org/moveFocus.js:362
("l")@/home/mike/.local/share/gnome-shell/extensions/putWindow@clemens.lab21.org/moveFocus.js:331
([object _private_Meta_Display],[object _private_Meta_Screen],null,[object _private_Meta_KeyBinding])@/home/mike/.local/share/gnome-shell/extensions/putWindow@clemens.lab21.org/moveFocus.js:151
"'
    JS ERROR: !!!     message = '"this._screens is undefined"'
```

**Comment by negesti** [comment] 2015-03-30 15:49
sry, forgot how funny javascript objects can be

**Comment by mijoharas** [comment] 2015-03-30 16:32
hmm... there still seems to be a problem:

```
JS ERROR: !!!   Exception was: TypeError: this.actor.set_pivot_point is not a function
    JS ERROR: !!!     lineNumber = '28'
    JS ERROR: !!!     fileName = '"/home/mike/.local/share/gnome-shell/extensions/putWindow@clemens.lab21.org/moveFocus.js"'
    JS ERROR: !!!     stack = '"([object _private_Meta_Rectangle],[object _private_Meta_Window])@/home/mike/.local/share/gnome-shell/extensions/putWindow@clemens.lab21.org/moveFocus.js:28
wrapper([object _private_Meta_Rectangle],[object _private_Meta_Window])@/usr/share/gjs-1.0/lang.js:204
([object _private_Meta_Rectangle],[object _private_Meta_Window])@/usr/share/gjs-1.0/lang.js:145
([object _private_Meta_Rectangle],[object _private_Meta_Window])@/usr/share/gjs-1.0/lang.js:239
([object _private_Meta_Window])@/home/mike/.local/share/gnome-shell/extensions/putWindow@clemens.lab21.org/moveFocus.js:124
([object _private_Meta_Window])@/home/mike/.local/share/gnome-shell/extensions/putWindow@clemens.lab21.org/moveFocus.js:131
([object Array])@/home/mike/.local/share/gnome-shell/extensions/putWindow@clemens.lab21.org/moveFocus.js:436
("l")@/home/mike/.local/share/gnome-shell/extensions/putWindow@clemens.lab21.org/moveFocus.js:352
([object _private_Meta_Display],[object _private_Meta_Screen],null,[object _private_Meta_KeyBinding])@/home/mike/
```

**Comment by negesti** [comment] 2015-03-30 16:39
The problem is now that the way animations are initialized has changed since 3.4.

I will check that...

Sry for the many trial and error runs. But it's really hard to test it in my ***** vm. Btw why do you want to use ubuntu 12?

**Comment by mijoharas** [comment] 2015-03-30 16:41
required for my job. :unamused:.

**Comment by mijoharas** [comment] 2015-03-30 16:44
but thanks for helping to support me with the plugin, if there's anything I can do to help let me know. I've not worked with gnome-extensions much, but I know javascript pretty well, so if you can explain how to go about debugging it I'll try and help.

**Comment by negesti** [comment] 2015-03-30 17:04
Every thing works expect the animation when chaning the focus. 

Quick fix, disable it by commenting flashWindow in _activateWindow.

A little bit harder is to find out a way to make Flashapot work with 3.4  e.g. find an alternative for actor.set_pivot_point. Best shot would by looking glas and inspecting an actor (alt + f2 - lg). Or find an other extenstion rhat uses animation an copy with prid ;)

**Comment by negesti** [comment] 2015-03-31 07:11
ok, removed the call to set_pivot_point. Animation still works and i can move the focus in 3.2

**Comment by mijoharas** [comment] 2015-03-31 08:58
I still have problems with this, I can go still go in one direction (from left screen to right) but still cannot go in the other direction, it appears to "try" to move (you see the same things happening to other windows) but it will not move.

There don't appear to be any errors emitted. How do I inspect an actor in looking glass? once I can get myself oriented w.r.t. debugging maybe I can help a little more. :smile: .

One interesting point is that I tried moving the displays to be in the other orientation (put the left on the right and vice versa) and I could still only move from the screen to the left to the screen to the right (which are now different screens), except now it emits an error. I'm not sure if this is a valid error though, as I changed the orientation of the screen while gnome-shell was still running (but it does still get emitted after a shell restart (`Alt-F2 r`)). Error is below:

```
"'
    JS ERROR: !!!     message = '"this.actor is undefined"'
    JS ERROR: !!!   Exception was: TypeError: this.actor is undefined
    JS ERROR: !!!     lineNumber = '128'
    JS ERROR: !!!     fileName = '"/home/mike/.local/share/gnome-shell/extensions/putWindow@clemens.lab21.org/moveFocus.js"'
    JS ERROR: !!!     stack = '"([object _private_Meta_Window])@/home/mike/.local/share/gnome-shell/extensions/putWindow@clemens.lab21.org/moveFocus.js:128
([object _private_Meta_Window])@/home/mike/.local/share/gnome-shell/extensions/putWindow@clemens.lab21.org/moveFocus.js:135
([object Array])@/home/mike/.local/share/gnome-shell/extensions/putWindow@clemens.lab21.org/moveFocus.js:440
("l")@/home/mike/.local/share/gnome-shell/extensions/putWindow@clemens.lab21.org/moveFocus.js:356
([object _private_Meta_Display],[object _private_Meta_Screen],null,[object _private_Meta_KeyBinding])@/home/mike/.local/share/gnome-shell/extensions/putWindow@clemens.lab21.org/moveFocus.js:153
"'
```

**Comment by mijoharas** [comment] 2015-03-31 09:00
To reiterate, not sure if the error is a "real one" as it is after a screen reconfiguration.

**Comment by negesti** [comment] 2015-03-31 10:10
that was a copy past error..
I can move the focus between two windows on the same screen. I tried to attach a second screen to my vm but failed...

**Comment by mijoharas** [comment] 2015-03-31 10:58
Ok, I'll try and get a debugging setup going and send a PR if I can fix it. Thanks for your help. :smile:

**Closed** 2015-06-08 13:38 UTC
Labels: Bug
