### ISSUE TITLE
App "jumps back" to specific workspace after I move it manually

### ISSUE THREAD

**Issue by lonix1** [negesti/gnome-shell-extensions-negesti#142] opened 2018-07-04 07:36 UTC
Suppose I have "move to workspace" for a certain app, then it launches on that workspace. BUT, if I later move the app manually, this extension will again move it back to the original workspace.

## Expected Behavior
If I manually move a app, the extension should not again reposition it.

## Current Behavior
The extension moves the app to a certain workspace. And later, will move it again. This is wrong - it should only move it the first time. Also, this indicates that it is polling, which is inefficient?

## Possible Solution
Move the app when it launches, then don't do it again. (and stop polling for it, if it's polling)

## Steps to Reproduce (for bugs)
1. set some app to launch on a certain workspace
2. launch it
3. manually move the app to a different workspace, or monitor - e.g. using <kbd>super-pg dn</kbd> or right-click window title and choose `Move to Workspace Down`
4. switch to different workspace, switch between apps, scroll between workspaces (I use `Desktop Scroller` extension for that) - i.e. just move around between your open apps
5. the app will automatically move back to the original workspace

## Context
I don't have any other extensions that move windows around.

## Your Environment
Ubuntu 18.04
extension version 23

**Comment by negesti** [comment] 2018-07-05 07:19
Thanks for reporting this. 
The extensions register a callback on the gnome display "window-created" event. Most of the code comes from the "official" MoveToWorkspace extension but is quite old. I think I have added the feature for gnome-shell 3.2

**Comment by lonix1** [comment] 2018-07-06 07:31
Ok so what you're saying is that it doesn't poll, which is great.

However back to the issue itself - is it just my setup, or is this reproducible? Or is it by design (I hope not :-)

**Comment by negesti** [comment] 2018-07-06 08:59
It's not by designed. However the whole "workspace related stuff" is ~ 5 years old and should be completely re-written or removed. 
INHO the current version of "AutoMoveWindows" supports everything I have implemented, better, "tried to implement", in putWindows.

**Comment by rrthomas** [comment] 2020-10-13 16:59
I have had this problem, specifically after restarting GNOME shell with the "r" command.

If I disable Put Windows, then restart GNOME shell, it works fine, so it seems that a simple fix would be for Put Windows to effectively shut down and restart when the desktop is restarted.

About "AutoMoveWindows": this extension very definitely does NOT replace Put Windows, as it only allows a window to be put on a specific workspace, not in a specific position, which is an excellent feature that I use!

Thanks very much for your work on PutWindows, and I hope you can fix this bug!

**Comment by negesti** [comment] 2024-08-15 15:38
Closing this, as application based config is no longer supported by this extension in gnome-shell v46

**Closed by negesti** 2024-08-15 15:38 UTC
