### ISSUE TITLE
placement issues with dash to dock

### ISSUE THREAD

**Issue by fastrizwaan** [negesti/gnome-shell-extensions-negesti#96] opened 2016-04-25 10:14 UTC
I'm trying to use dash as unity panel (always visible), in fedora 23, With dash to dock extension enabled on left side always visible, put windows does not align/place  the windows properly, it is discarding the pixels utilized by "dash-to-dock" 

please see this: notice that the top left and bottom left are place behind the dock.
![screenshot from 2016-04-25 15-34-52](https://cloud.githubusercontent.com/assets/1161682/14780697/ccb5f710-0afb-11e6-9d75-b4f4172d32ea.png)

But it should be like this:
![screenshot from 2016-04-25 15-36-27](https://cloud.githubusercontent.com/assets/1161682/14780757/15214f2c-0afc-11e6-9015-3a3543fd9b24.png)

the left (ctrl+alt+4) works as expected, but ctrl+alt+6 (place right side does not take the dash space into consideration) but super+right (gnome-shell's shortcut) works as expected

![screenshot from 2016-04-25 15-42-23](https://cloud.githubusercontent.com/assets/1161682/14780824/648a0fb8-0afc-11e6-9289-9e487ada8da3.png)

Please try to improve window placement with dash-to-dock extension, which is one of the most popular gnome-shell extensions.

Thanks.

**Comment by fastrizwaan** [comment] 2016-04-25 10:40
just discovered, that installing (re-enabling) put windows after dash-to-dock extension, make it works, but as soon as I restarted the shell, (alt+f2, r), the window bottom left got messed up. (re-enabling) causes the bottom-left window to not align at the bottom edge, please see this, observe the wallaper is visible in the bottom-left
![screenshot from 2016-04-25 16-07-26](https://cloud.githubusercontent.com/assets/1161682/14781459/35bf7534-0b00-11e6-997b-abec37a87b95.png)

**Comment by negesti** [comment] 2016-04-25 10:45
looks strange. can you confirm this behavior with other windows/applications. some apps are reporting a wrong combination of size, margin and padding and the positioning is messed up. 
nautilus and terminal usually work best

**Comment by fastrizwaan** [comment] 2016-04-25 11:02
I usually press super+5 then super+1 (center then put on bottom left)

![screenshot from 2016-04-25 16-25-46](https://cloud.githubusercontent.com/assets/1161682/14781812/8374d448-0b02-11e6-8c4a-e59b43b07a90.png)

![screenshot from 2016-04-25 16-26-38](https://cloud.githubusercontent.com/assets/1161682/14781819/87cec72e-0b02-11e6-8245-5a8608b0a818.png)

Nautilus, gnome-terminal, firefox and gedit are having same issue at the bottom edge of the screen for 1st action (super+5 then super+1 or super+3), but on 2nd action (super+5, super+1, super+1) properly takes up the bottom space, but the window size is different than (super+5). thanks.

please observe the gedit window (super+5, then super+1, and super+1) 2nd,3rd, action works as expected.
![screenshot from 2016-04-25 16-29-50](https://cloud.githubusercontent.com/assets/1161682/14781876/feb3d82a-0b02-11e6-9a11-dab77422d5f3.png)

I want a window to be quarter size 1/4th of the available window space, so that I could stack 4 windows for monitoring, I usually do 3 windows (2 on top left and bottom left and 1 on right)

Thanks.

**Comment by negesti** [comment] 2016-04-25 15:51
i checked the code again and the problem is, that the calculated position is correct. You can check this by adding an appropriate global.log line at extension.js#_resize (line 735).
Some application (like gedit) just "ignore" the coordinates passed to move_resize_frame and move "somwhere near" the given position.

**Comment by fastrizwaan** [comment] 2016-04-27 16:49
hi, I don't know how to add global.log at line 735

 // actual resizing
  _resize: function(win, x, y, width, height) {
    let maximizeFlags = 0;

where should I put global.log line?

**Comment by fastrizwaan** [comment] 2016-04-27 16:51
Also, another bug is that everytime we have to disable and re-enable putwindows extension using gnome-tweak-tool to have it working with dash-to-dock extension, if we restart the machine or restarted gnome-shell.

**Comment by fastrizwaan** [comment] 2016-04-27 16:54
also, if we do super+5, super+5 (maximize the window) then do a super+1 or super+3, then it is working as expected.

**Comment by negesti** [comment] 2016-04-28 09:43
@fastrizwaan I added an additional listener, that reloads the usable screen size. enable/disable the extension to make it work with dash to dock should no longer be required

Regarding the log message. using 100% of the available space would be indeed very nice. Calculating the position and size looks easy at the first glance but is quite difficult when you start adding padding/margin into the calculation. 
The current version works for most applications and I have not found a combination of applications which results in overlapping windows. 

If you want to investigate this and calculate the positions, my suggestions is to restart the shell in a terminal using `gnome-shell --replace &` and add some global.log cals to "debug" what you are calculating. My first stept would be to add
`global.log("x: " + x + " y " + y + " width " + width + " height " + height);`
add the beginning and end of the _resize function.

Note, that some applications like gnome-terminal resizing them manually doesn't support every combination of width/height too. i.e. A typical terminal has a width of 80 chars and can only be resized to 81 chars but not to 80.2. 
Mutter MetaWindow documentation for the resize function: https://developer.gnome.org/meta/3.8/MetaWindow.html#meta-window-move-resize-frame

**Comment by negesti** [comment] 2016-08-26 13:05
Closing this issue as placement with dash to dock is working after adding the new listener.

**Closed by negesti** 2016-08-26 13:05 UTC

**Comment by ahmadnassri** [comment] 2017-11-03 02:35
this still seems to be an issue for vertical orientations
