### ISSUE TITLE
Moving windows no longer working lately

### ISSUE THREAD

**Issue by elmerehbi** [negesti/gnome-shell-extensions-negesti#138] opened 2018-02-24 19:39 UTC
I have been using this extension for a whiel however recently moving windows between the main display and an external monitor (in landscape mode) stopped working. It only moves focus to the other monitor.

May that be a bug?

**Comment by negesti** [comment] 2018-02-26 07:30
hm, works here. Maybe "Move Focus" is enabled and uses the same key binding?

**Comment by elmerehbi** [comment] 2018-02-27 20:43
@negesti You're right and I have thought of this however I didn't change any settings lately. Maybe this is a conflict following some update?

I have changed the key bindings for the focus to `Super+Shift+Ctrl+Left/Right`.

**Comment by negesti** [comment] 2018-02-28 09:48
Thanks for you feedback. I will check the pull requests #136 and #137 maybe something was changed there

**Comment by horga83** [comment] 2018-04-13 18:06
Antergos Linux with latest updates, 4 static workspaces and two monitors.

Does not seem to work for all windows.  Gnome-terminal works but Firefox doesn't, Chromium doesn't, Evolution seems to. Gedit doesn't move to other monitor, in short it's very inconsistent.  Gedit for example changed it's size but did not move to screen 2 as configured, so something happens but not the correct thing.  Very interested in debugging this with your help.

**Comment by TheRoarkster** [comment] 2018-05-08 17:40
I'm having this problem too.  It used to auto-move windows between Workspaces based on per-application settings.  After upgrade to Fedora 28 (GNOME 3.28), some applications respect the settings (e.g., gnome terminal) and some don't (e.g., Firefox and Chromium).  

I can help debug too.  

Also, is there a support/contribution/tip jar?  I do not exaggerate when I say that this extension is the reason I use GNOME.  I cannot understand how people function on any OS that just opens windows wherever the OS wants.   That is insanity.

**Comment by negesti** [comment] 2018-05-09 05:42
Just tried with gedit and firefox and both work for me :(

* Please check if the key binding is used somewhere else
* Does the "configuration" work for application "All" ?
* Any error/exceptions if you run `gnome-shell --restart & ` in terminal?

**Comment by TheRoarkster** [comment] 2018-05-09 18:59
Really?  That's odd.  Are you on GNOME 3.28 in Fedora 28? 

I just tried it with a fresh install of Ubuntu 18.04, and it seems to retain the Workspace settings (i.e., it works).  But one glitch is that the **Window Target Workspace** number always reverts to 0 -- even if it is set to Workspace 1 or Workspace 2.  

I will try the suggestions when I switch over to Fedora later.

**Comment by horga83** [comment] 2018-05-10 04:29
Firefos does not work for me.  I am on Arch (Antergos) with gnome-shell 
3.28.1.  What do you mean "key binding", there are no key bindings for
this extension.  Also what does the configuration "all" mean?  Gnome-
shell 3.28 doesn't have a --restart option from the command line, did
you mean "replace"?
George

**Comment by horga83** [comment] 2018-05-10 15:41
I forgot to mention that this only fails with Firefox when I have two
monitors running, so multiple monitor support is not working well.  If
I disable the second monitor it works fine.
George

**Comment by elmerehbi** [comment] 2018-05-10 16:17
I can also confirm that is working for me (Gnome Shell 3.18.5 on Ubuntu Gnome 16.04 ). Maybe it is a conflict with something else? Have you installed another software recently?

**Comment by TheRoarkster** [comment] 2018-05-10 17:13
I accessed another Fedora 28 install, one that was an upgrade from Fedora 27, on a different machine.  And it works.  So it is just on a **fresh/clean Fedora 28** install (for me) that it didn't work.

**Comment by negesti** [comment] 2018-05-14 13:04
@horga83 
* you're right it's `--replace` 
* I mean keyboard binding/shortcuts 
* You can configure position and size for an individual application or just configure different position and sizes for "All"

There was a bug when trying to move or resize a already maximized window. Does it work with firefox, if the current window is not maximized?

I can create a Fedora 28 VM and test the extension there. But that will take some time.

Please check if your Fedora 28 installation is running wayland. The extension does not work properly with wayland

**Comment by negesti** [comment] 2018-05-14 13:08
@TheRoarkster "Move to workspace" is based on the "official" gnome extension "Auto-Move-Window". But the feature was added about 2 years ago e.g. maybe a fresh "copy" of the auto-move-window would resolve the issue

**Comment by negesti** [comment] 2018-05-14 16:19
Just tried with a fresh installation of fedora 28 inside a vm. 
1. Using wayland I was not able to start gnome-shell at all
1. Using "Gnome Xorg" works 
1. Installed and successfully tested github release 

Unfortunately i'm not able to add a second monitor to my vm :(

**Comment by negesti** [comment] 2018-06-21 15:57
Any feedback? Can i close the ticket?

**Comment by horga83** [comment] 2018-06-21 22:18
Well moving Firefox still does not work with multiple monitors.

**Comment by negesti** [comment] 2018-06-22 06:22
@horga83 that's strange. just tried again and can move firefox between screens without problems :(
 - using put windows shift + super + left/right to move to other screens
 - using gnome-shells shift + ctrl + left/right to move to other screens
 - add a configuratoin to put windows to move it between screens (both maximized and 'smaller')
 - add a config to put windows and auto-move it on creation

You are using fedora 28 with shell 3.28?
Any error when running `gnome-shell --replace &` from bash?
Are you using the latest version of the extension? (both github and extension.gnome.org are up to date)

**Comment by negesti** [comment] 2018-10-25 15:35
The move to workspace feature is based on the official "Auto-Move-Windows" extension. I will try to debug is further i find have some time off

**Comment by TheRoarkster** [comment] 2018-10-25 15:56
Sounds good.  FWIW, the official "Auto-Move-Windows" itself **does** work.  I just tried it with an app that doesn't work in "Put Windows."

**Comment by horga83** [comment] 2018-10-25 20:34
On Thu, 2018-10-25 at 15:57 +0000, TheRoarkster wrote:
> Sounds good. FWIW, the official "Auto-Move-Windows" itself does work.
> I just tried it with an app that doesn't work in "Put Windows."
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.

Actually it doesn't work if you have multiple monitors.  For example
Auto-Move-Windows will work fine on a single monitor, however, it will
only work with certain apps on dual monitors.  Evolution seems to work
fine, Firefox does not, it always opens on the current workspace.

This has been a problem for a long time.

Cheers
George

**Comment by TheRoarkster** [comment] 2019-03-11 21:26
@horga83, I only use one monitor, so I can't replicate the Auto-Move-Windows problem for two.  But I can confirm that Put Windows is not able to consistently open applications in the designated workplace on one monitor.  For some reason, the number set for the workspace always reverts to 0.

**Comment by negesti** [comment] 2024-08-15 15:39
Closing this, as application based config is no longer supported by this extension in gnome-shell v46

**Closed by negesti** 2024-08-15 15:39 UTC
Labels: Type: Bug, Pending
