### ISSUE TITLE
Missing support for gnome-shell 3.22

### ISSUE THREAD

**Issue by spapanik** [negesti/gnome-shell-extensions-negesti#109] opened 2016-11-18 08:26 UTC
Please support gnome-shell 3.22

**Comment by negesti** [comment] 2016-11-18 10:00
I will upgrade to Fedora 25 on the weekend and update the extension

**Comment by negesti** [comment] 2016-11-21 08:32
looks like the settings are not working properly: 
* Keybinding super + shift left/right is now used by gnome
* adding application based config does not work

**Comment by negesti** [comment] 2016-11-24 11:52
after using the extension in 3.22 for some days, i found some really annoying bugs. This will take some time :(

**Comment by donateur** [comment] 2017-01-02 09:01
Hello,

You've said this will take some time to work out X11 support for gnome shell 3.22.  I was wondering, how long would you expect it to take to get the extension working with wayland?

Thanks

**Comment by negesti** [comment] 2017-01-03 13:14
I tried it with wayland and had some problems with the keybindings. Mostly because some keybindings are used by gnome-shell and after removing the binding from gnome, they are not forwarded to the extension. However this seems to work after a shell restart,

The other more annoying problem is, that libwnck regularly causes a segfault when i open the prefs window in wayland and i can not find a better way to get the name of all running apps. I have tried the app chooser, but it wont it only show's application to open files. e.g. things like gnome-terminal are not available inside the app chooser.

**Comment by GabLeRoux** [comment] 2017-01-13 19:26
```
$ gnome-shell --version
GNOME Shell 3.22.2
```

And the plugin seems to work fine for me on arch
```
$ uname -a
Linux zbookarch.local 4.8.13-1-ARCH #1 SMP PREEMPT Fri Dec 9 07:24:34 CET 2016 x86_64 GNU/Linux
```

I'm not using much features from this tought. Only the move to corners, which is actually broken for me with multiple windows which is #94

**Comment by negesti** [comment] 2017-01-14 08:54
Yeah that's true it works with 3.22 at least if you use x11 and not Wayland. That's why 3.22 is not "officially" supported.

**Comment by 73** [comment] 2017-01-19 10:32
```
[$] gnome-shell --version
GNOME Shell 3.22.2
```
... on X11

No Shortcut `WIN+<X>` is working. When I try to assign one it just does not register the Win key.

**Comment by negesti** [comment] 2017-01-19 14:04
that's strange, can you try to start the preferences from command line? Maybe something useful is logged: 

                         gnome-shell-extension-prefs putWindow@clemens.lab21.org

**Comment by arigit** [comment] 2017-01-22 19:13
I tried the extension with Fedora 25 on Wayland, and it didn't resize & relocate windows as it does on X11 logins. Really looking forward to Wayland support on this great extension

**Comment by negesti** [comment] 2017-01-22 19:26
I was using it with Wayland when Fedora 25 was released and switched back to x11 after starting gnome boxes for the first time...

I had to disable some gnome keyboard bindings and restart the shell e.g. reply but it worked. "Only" the preferences window is buggy

**Comment by arigit** [comment] 2017-03-12 18:37
@negesti - do you mean that window application size & location worked for you on wayland?
Just retested with an updated fedora 25 on wayland, and "Put Window" master as of today and still finding the same problem.
Further, when in the Preferences window > Applications > "+", I get this error:  "Error getting running apps" "We were not able to get thie list of running apps from Wnck. Are you running Wayland"?

At this point the only item holding me from swithing to Wayland full time is this extension, I got so used to it :)
As we know wayland enables stronger security than X11 and is the way foward, so truly looking forward to seeing wayland support added to Put Window

**Comment by negesti** [comment] 2017-03-13 11:35
The "normal" window movement works using wayland. The "only" problem you have is, that the application based configuration does not work with wayland?

I have an auto-move rule for skype and an "All" rule to move windows between my two screens. Both rules work as expected with X11 and wayland. Although I'm not sure if skype just restores the old location or is really move when created. I have never moved that window :)

The problem with Preferences window > Applications > "+" is related to libwnck which I use to get the list of running applications. While this works fine under X11, libwnck segfaults when called in an wayland environment. Unfortunately I have not found any alternative to libwnck that works with wayland. Using the gnome-shell "open with" dialog like the Atuo-Move windows extension does is no option in my opinion as does not show all applications.

**Comment by negesti** [comment] 2017-05-04 15:42
Closing this as 3.22 is supported and the problem is a proper wayland support

**Closed by negesti** 2017-05-04 15:42 UTC
Labels: In Progress
